### ISSUE TITLE
Error when the liouvillian has no real eigenvalues 

### ISSUE THREAD

**Issue by bradleyharden** [gbouvignies/ChemEx#13]
Hi Guillaume,

Thanks for ChemEx! It was quite easy to use once I understood the structure. I do have a few bugs to report though.

First, in the n_iph type CEST experiments, it appears that there is no check to verify that there is at least one real eigenvalue when diagonalizing the liouvillian in back_calculation.py. In a few instances I had sl2 come back empty, throwing an error when used a few lines later. Adjusting the initial parameters for the fit resolved the problem in all the cases I encountered. I think the optimization had just run amok into physically impossible values. Maybe a grid search or some other strategy prior to optimization might resolve this? I think ChemEx was also having trouble finding the correct value for dw if I didn't get it at least close to begin with. Would a grid search help here as well?

I'm guessing that this problem is more general than n_iph_cest, but I haven't looked through any of the other experiments.

**Comment by bradleyharden** [comment]
On second thought, after reading Dr. Hansen's suggested strategy for fitting kex and pb locally, perhaps this isn't that big of an issue after all. I think these cases may have been caused by physically impossible values of kex and delta r2, or something similar. If I had isolated the failing residues by properly using the +r flag, correcting the initial parameters would have been more straightforward. However, it would still be nice to get a more intuitive error message in cases like this.

**Comment by gbouvignies** [comment]
Hi Bradley,

Sorry for being so late to answer you.

I am not sure what precisely causes the issue, but for sure it would be nicer to catch the error and print a more informative message when that happens.

If you still have that calculation, could you please send it to me? 

By the way, I am currently working on an update in which parameters can be bounded. I believe this should solve the issue.
