### ISSUE TITLE
Complex values in the parameters.fit file

### ISSUE THREAD

**Issue by bradleyharden** [gbouvignies/chemex#14]
Occasionally I find that all of the values in my parameters.fit file are complex numbers. Presumably the "par" array is converted to a complex array at some point? The vast majority of the values have zero imaginary part, but there are usually a handful of I0 values that have zero real part and an imaginary part that would be normal if it were in the real part.

**Comment by viochemist** [comment]
Hello,

This to me sounds like a bad initial parameterization. Can you provide example data where you get this behavior?

**Comment by bradleyharden** [comment]
Yes, I was just able to reproduce the behavior. Interestingly, when starting from a slightly different KEX value (330 vs 340), different residues now have imaginary values of I0. I'm not very familiar with github. Is there an easy way for me to upload the data here? Or should I email it to you?

**Comment by viochemist** [comment]
Can data be attached to the comments/issues? Otherwise I'd say email,
except that I'm on vacation right now and not capable of really looking at
the data.

**Comment by bradleyharden** [comment]
Ha! I should have read below: "Attach files by ..." Sorry about that. It looks like it won't accept .tgz files though. Here's a dropbox link: https://www.dropbox.com/s/fszhonbtbb2gbs2/complex_output.tgz?dl=0

**Comment by viochemist** [comment]
Has this been resolved? I'm just going through some of the old 'issues' while I have some free time at ENC.

**Comment by bradleyharden** [comment]
I haven't worked with ChemEx since I last posted. I never attempted to track down the bug, so presumably it has not been resolved.

**Comment by gbouvignies** [comment]
Hello,

Going through the files that Bradley attached to the issue, I realized that the profiles do not contain the intensity of the reference plane. Without this point, the parameters I0 and r_Nz are highly misdefined, likely leading to crazy complex values in the covariance matrix that is used to estimate the fitting parameter uncertainties. As expected, fixing r_Nz during the fit appears to solve the issue.

Bradley, if you have recorded a reference plane, you should add it to your profile file with an offset strictly less than -1e5 (this value is used as a flag for identifying reference planes).

Should we close the issue?

**Comment by bradleyharden** [comment]
Hi Guillaume,

Yes, with the fitting protocol I used to generate the CEST profiles, they were already normalized. I remember explicitly choosing to leave the reference plane out, and I remember thinking that there was a good reason to assume that the reference would default to one. However, clearly that's not the case. I will add the reference planes and see if the issue is resolved. Sorry for the confusion. Feel free to close the issue if you're confident that is the source of the problem.

**Comment by gbouvignies** [comment]
I close it for now. Let me know if adding the reference point doesn't solve the issue.
