### ISSUE TITLE
Locally fitting KEX and PB

### ISSUE THREAD

**Issue by bradleyharden** [gbouvignies/chemex#16]
One of the biggest issues I had with ChemEx was figuring out how to fit KEX and PB independently for each residue. I don't know if there is a better way to do it, but I ended up creating a new n_iph_cest type experiment with an edited data_point.py file to include "nucleus_name" as part of the KEX and PB tuples in short_long_par_names. This worked well enough, but there were still two small issues.

First, KEX and PB retain their "global" status in the parameters.fit file, even though there is a value for every residue. They are also written in a different format than all of the other parameters. It would seem to me that truly "global" parameters could be auto-detected in the same manner as the optimization clusters are identified.

Second, switching between a global and local fit of KEX and PB is not trivial. I would have thought this would be something you could do within a method file, but because it requires a different experiment type, it requires a different experiment file. I don't see an immediate, simple way to implement this though. In general, it would be nice to have a global/local toggle for every parameter.

**Comment by viochemist** [comment]
Hello Bradley

Thanks for providing feedback on ChemEx. Individual during can most efficiently be done by providing the residue (or residues) in the ChemEx command line using '+r'. For example:

chemex fit -e ... -p ... -o ... +r A72N-HN

This creates an A72N directory inside the output directory so that you don't have to change the output name. One can simply script all of the desired residues to be fit individually.

 If you include several residues, then the output will go into the output directory itself.

Similarly, one can exclude certain residues with the -r flag.

I hope this helps.

**Comment by bradleyharden** [comment]
Yes, I did use the 'r' flag to limit myself to the residues for which there was evidence of slow exchange peaks. However, I did not think to loop ChemEx over those residues individually. Does each residue then have its own parameters.fit file in each directory? Or is ChemEx smart enough to compile everything into one file somehow? If not, it seems a bit less than ideal, especially since the architecture for global vs. local parameters exists and clustering is already implemented. With my solution, I only have to point ChemEx to different experiment files and everything gets fit individually and compiled into one directory and parameter.fit file automatically. All that being said, the difference is really minimal. Thanks again for all your hard work!

**Comment by viochemist** [comment]
Each residue does have its own parameters.fit file, but these are read
easily using the parser (ArgParse) libraries in python. This is not dinner
automatically, however.

I think we prefer not to make the residue part of the global "long names"
as it becomes difficult to switch between global and individual fitting.
Plus, individual fitting frequently results in highly correlated parameters
leading to nonsensical values. For instance, I would recommend NOT fitting
delta r2 in CEST fits if done individually as this is highly correlated
with kex.

Guillaume will be able to comment better on the parameter handling, however.

**Comment by bradleyharden** [comment]
Oh yes! I remember seeing that library used for reading the parameter and method files. I believe you mean ConfigParser rather than ArgParse though. I don't know why I didn't put 2 and 2 together; the output file is the same format.

Yes, that does seem like a better approach. I had built my own parser for the output file, but this is much better.

On a different note, I didn't know that kex and delta r2 are highly correlated. Are there any other strongly correlated parameters that I should be aware of? Is there a discussion of the more practical details of CEST fitting in the literature that I missed?

Thanks for all your help!

**Comment by bradleyharden** [comment]
On thing I just noticed: files ending in .cfg automatically use correct syntax highlighting for me in vim (default vim in Ubuntu 14.04). On the other hand, the parameters.fit file does not show up with any syntax highlighting. Would it be worth it to switch the default file name to parameters.cfg to emphasize the format of the file?
