### ISSUE TITLE
missing 1 required positional argument: 'params'

### ISSUE THREAD

**Issue by BodhisatwaNandi** [gbouvignies/ChemEx#167]
Hi,

I am using chemex2022.3.4  installed in a conda environment with python3.10. The chemex command runs fine, showing that the installation has been done. However, when I am running the fit command, I get the error: 
Starting the fits...
                                                   
 ────────────── Running STEP1 (1/2)  ──────────────
                                                   
  • Selecting profiles -> 10 profiles
  • Fit method -> leastsq
  • Running the minimization...

     Iteration            χ²    Reduced χ²
    ───────────────────────────────────────
Traceback (most recent call last):
  File "/home/bodhi/anaconda3/envs/chemex/bin/chemex", line 10, in <module>
    sys.exit(main())
  File "/home/bodhi/anaconda3/envs/chemex/lib/python3.10/site-packages/chemex/chemex.py", line 88, in main
    args.func(args)
  File "/home/bodhi/anaconda3/envs/chemex/lib/python3.10/site-packages/chemex/chemex.py", line 76, in run
    run_fit(args, experiments)
  File "/home/bodhi/anaconda3/envs/chemex/lib/python3.10/site-packages/chemex/chemex.py", line 39, in run_fit
    run_methods(experiments, methods, args.output, args.plot)
  File "/home/bodhi/anaconda3/envs/chemex/lib/python3.10/site-packages/chemex/optimize/fitting.py", line 156, in run_methods
    _fit_groups(
  File "/home/bodhi/anaconda3/envs/chemex/lib/python3.10/site-packages/chemex/optimize/fitting.py", line 100, in _fit_groups
    best_lmfit_params = minimize_with_report(
  File "/home/bodhi/anaconda3/envs/chemex/lib/python3.10/site-packages/chemex/optimize/minimizer.py", line 89, in minimize_with_report
    minimizer.minimize(method=fitmethod, **(kws.get(fitmethod, {})))
  File "/home/bodhi/.local/lib/python3.10/site-packages/lmfit-1.0.3-py3.10.egg/lmfit/minimizer.py", line 2352, in minimize
    return function(**kwargs)
  File "/home/bodhi/.local/lib/python3.10/site-packages/lmfit-1.0.3-py3.10.egg/lmfit/minimizer.py", line 1689, in leastsq
    lsout = scipy_leastsq(self.__residual, variables, **lskws)
  File "/home/bodhi/.local/lib/python3.10/site-packages/scipy-1.8.1-py3.10-linux-x86_64.egg/scipy/optimize/_minpack_py.py", line 410, in leastsq
    shape, dtype = _check_func('leastsq', 'func', func, x0, args, n)
  File "/home/bodhi/.local/lib/python3.10/site-packages/scipy-1.8.1-py3.10-linux-x86_64.egg/scipy/optimize/_minpack_py.py", line 24, in _check_func
    res = atleast_1d(thefunc(*((x0[:numinputs],) + args)))
  File "/home/bodhi/.local/lib/python3.10/site-packages/lmfit-1.0.3-py3.10.egg/lmfit/minimizer.py", line 587, in __residual
    out = self.userfcn(params, *self.userargs, **self.userkws)
  File "/home/bodhi/anaconda3/envs/chemex/lib/python3.10/site-packages/chemex/containers/experiments.py", line 37, in residuals
    list(
  File "/home/bodhi/anaconda3/envs/chemex/lib/python3.10/site-packages/chemex/containers/experiments.py", line 38, in <genexpr>
    chain.from_iterable(experiment.residuals(params) for experiment in self)
  File "/home/bodhi/anaconda3/envs/chemex/lib/python3.10/site-packages/chemex/containers/experiment.py", line 34, in residuals
    return list(
  File "/home/bodhi/anaconda3/envs/chemex/lib/python3.10/site-packages/chemex/containers/experiment.py", line 35, in <genexpr>
    chain.from_iterable(profile.residuals(params) for profile in self.profiles)
  File "/home/bodhi/anaconda3/envs/chemex/lib/python3.10/site-packages/cachetools/decorators.py", line 68, in wrapper
    k = key(*args, **kwargs)
TypeError: _cache_key() missing 1 required positional argument: 'params'

The problem is same with the example dataset as well.
Any help is highly appreciated.

Thank you.
Bodhisatwa

**Comment by gbouvignies** [comment]
Hi Bodhisatwa,

I've tried to reproduce the issue you encountered with ChemEx 2022.3.4, but haven't succeeded so far.

I created the following conda environment:

```bash
conda create -n ChemEx-2022.3.4 -c conda-forge python=3.10 chemex=2022.3.4 pydantic=1.10
conda activate ChemEx-2022.3.4
```

I then ran the "CEST_15N" and "CPMG_15N_IP" examples. All went fine.

Could you please provide me with the following information:

* The exact `conda` environment you are using – or the output of the `conda list` command.
* A minimal example that generates the error message – or a link to the example dataset that you are using.

Thanks,
Guillaume

**Comment by BodhisatwaNandi** [comment]
Hello Sir,
This is the output of the conda list command: 
#packages in environment at /home/bodhi/anaconda3/envs/chemex:

#Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             5.1                       1_gnu  
appdirs                   1.4.4              pyhd3eb1b0_0  
asteval                   0.9.29             pyhd8ed1ab_0    conda-forge
astunparse                1.6.3                    pypi_0    pypi
blas                      1.0                         mkl  
brotli                    1.0.9                h5eee18b_7  
brotli-bin                1.0.9                h5eee18b_7  
brotlipy                  0.7.0           py310h7f8727e_1002  
bzip2                     1.0.8                h7b6447c_0  
ca-certificates           2023.05.30           h06a4308_0  
cachetools                4.2.2              pyhd3eb1b0_0  
certifi                   2023.5.7        py310h06a4308_0  
cffi                      1.15.1          py310h5eee18b_3  
charset-normalizer        2.0.4              pyhd3eb1b0_0  
chemex                    2022.3.4           pyhd8ed1ab_0    conda-forge
contourpy                 1.0.5           py310hdb19cb5_0  
cryptography              39.0.1          py310h9ce1e76_2  
cycler                    0.11.0             pyhd3eb1b0_0  
fonttools                 4.25.0             pyhd3eb1b0_0  
freetype                  2.12.1               h4a9f257_0  
future                    0.18.3          py310h06a4308_0  
giflib                    5.2.1                h5eee18b_3  
idna                      3.4             py310h06a4308_0  
intel-openmp              2023.1.0         hdb19cb5_46305  
jpeg                      9e                   h5eee18b_1  
kiwisolver                1.4.4           py310h6a678d5_0  
lcms2                     2.12                 h3be6417_0  
ld_impl_linux-64          2.38                 h1181459_1  
lerc                      3.0                  h295c915_0  
libbrotlicommon           1.0.9                h5eee18b_7  
libbrotlidec              1.0.9                h5eee18b_7  
libbrotlienc              1.0.9                h5eee18b_7  
libdeflate                1.17                 h5eee18b_0  
libffi                    3.4.4                h6a678d5_0  
libgcc-ng                 11.2.0               h1234567_1  
libgfortran-ng            11.2.0               h00389a5_1  
libgfortran5              11.2.0               h1234567_1  
libgomp                   11.2.0               h1234567_1  
libpng                    1.6.39               h5eee18b_0  
libstdcxx-ng              11.2.0               h1234567_1  
libtiff                   4.5.0                h6a678d5_2  
libuuid                   1.41.5               h5eee18b_0  
libwebp                   1.2.4                h11a3e52_1  
libwebp-base              1.2.4                h5eee18b_1  
lmfit                     1.2.0              pyhd8ed1ab_0    conda-forge
lz4-c                     1.9.4                h6a678d5_0  
markdown-it-py            2.2.0           py310h06a4308_1  
matplotlib-base           3.7.1           py310h1128e8f_1  
mdtraj                    1.9.7                    pypi_0    pypi
mdurl                     0.1.0           py310h06a4308_0  
mkl                       2023.1.0         h6d00ec8_46342  
mkl-service               2.4.0           py310h5eee18b_1  
mkl_fft                   1.3.6           py310h1128e8f_1  
mkl_random                1.2.2           py310h1128e8f_1  
munkres                   1.1.4                      py_0  
ncurses                   6.4                  h6a678d5_0  
numpy                     1.24.3          py310h5f9d8c6_1  
numpy-base                1.24.3          py310hb5e798b_1  
openssl                   3.0.9                h7f8727e_0  
packaging                 23.0            py310h06a4308_0  
pillow                    9.4.0           py310h6a678d5_0  
pip                       23.1.2          py310h06a4308_0  
pooch                     1.4.0              pyhd3eb1b0_0  
pycparser                 2.21               pyhd3eb1b0_0  
pydantic                  1.10.8          py310h5eee18b_0  
pygments                  2.15.1          py310h06a4308_1  
pyopenssl                 23.0.0          py310h06a4308_0  
pyparsing                 3.0.9           py310h06a4308_0  
pysocks                   1.7.1           py310h06a4308_0  
python                    3.10.12              h955ad1f_0  
python-dateutil           2.8.2              pyhd3eb1b0_0  
rapidfuzz                 2.13.7          py310h1128e8f_0  
readline                  8.2                  h5eee18b_0  
requests                  2.29.0          py310h06a4308_0  
rich                      13.3.5          py310h06a4308_0  
scipy                     1.10.1          py310h5f9d8c6_1  
setuptools                67.8.0          py310h06a4308_0  
setuptools-scm            7.1.0           py310h06a4308_0  
six                       1.16.0             pyhd3eb1b0_1  
sqlite                    3.41.2               h5eee18b_0  
tbb                       2021.8.0             hdb19cb5_0  
tk                        8.6.12               h1ccaba5_0  
tomli                     2.0.1           py310h06a4308_0  
typing-extensions         4.6.3           py310h06a4308_0  
typing_extensions         4.6.3           py310h06a4308_0  
tzdata                    2023c                h04d1e81_0  
uncertainties             3.1.7              pyhd8ed1ab_0    conda-forge
urllib3                   1.26.16         py310h06a4308_0  
wheel                     0.38.4          py310h06a4308_0  
xz                        5.4.2                h5eee18b_0  
zlib                      1.2.13               h5eee18b_0  
zstd                      1.5.5                hc292b87_0  

Nevertheless, I removed the conda environment and reinstalled it with the command line that you provided :
conda create -n ChemEx-2022.3.4 -c conda-forge python=3.10 chemex=2022.3.4 pydantic=1.10
It is working perfectly fine now. I believe the issue was some mismatching package. Thanks a lot for your time and kind help.

Best regards,
Bodhisatwa Nandi

**Comment by gbouvignies** [comment]
Great! I'm glad that creating a fresh environment solved your issue. Please let me know if you have any other questions.
