### ISSUE TITLE
How to open chemex in a graphic user interface

### ISSUE THREAD

**Issue by shengliwang** [gbouvignies/chemex#18]
Hi Guillaume
      I am a Chinese man, and also a fresher of Python. Now, I have already install chemex using the given steps on the site. But I do not konwn how to use it? How to runing the program.
      Thanks!!!

**Comment by viochemist** [comment]
Hello Shengli,

At present, chemex does not have a graphical interface, it is command line only. If you type 'chemex' on the command line it will bring up some helpful information on the syntax and requirements for each experiment type. Also, if you navigate to the 'examples' directory in chemex you'll find a number of practice data for CPMG and CEST experiments and our recommended organization of files. 

- data - location of residue-specific files containing experimentally determined intensities
- experiments - configuration files providing details of the recorded experiment
- parameters - configuration files to provide initial fitting parameters
- input (optional) - files for residue-specific initial parameters (ie. chemical shift, R1, R2 ...)
- methods (optional) - instructions for chemex on what parameters to fit/fix
- output - where you'll put your results

In each experiment there is a 'run' file which contains variations on how to run chemex: globally, individual residue, excluding a residue, and using a method.

**Comment by shengliwang** [comment]
Hi
Thanks for your responding. I now know how to use it with your help.
