### ISSUE TITLE
Grid search error (15N CEST fitting)

### ISSUE THREAD

**Issue by MsMorozka** [gbouvignies/ChemEx#196]
Good morning, I am trying to fit 15N CEST data. My "invisible" state is quite poorly populated, however I  wish to extract K_ex and R2_B, values. 

I have performed graphical fitting, but the output values look inadequate (R2_B = 2.22027e-05 # (error not calculated)). I suspect that the issue lies in the "initial" parameters like as  PB, Kex_AB, and i inserted my experemental data of R1_A and R2_A and "FIX" via methods R2_B and DW_AB.

 And unfortunatelly,  I cannot run the grid search as well (according to  the example) , I got this error - **Error: UnicodeEncodeError: 'charmap' codec can't encode characters in position 12-13: character maps to <undefined>**. 

I would appreciate any kind of help, thank you in advance
Regards, Nataliia

**Comment by gbouvignies** [comment]
Hello Nataliia,

To help investigate the issue, could you share the method.toml file causing this error? A potential cause could be the file's encoding. If it's not in UTF-8, converting it to this format might resolve the error. Please check and confirm the file's encoding.

**Comment by MsMorozka** [comment]
Good morning, thank you a lot for your answer!
Yes, the file encoding is UTF-8. However the error is still present. ( even if I run the example file "CPMG_15N_IP")
 The full error message:
 
 `Traceback (most recent call last):
  File "C:\Users\1\anaconda3\envs\example\Scripts\chemex-script.py", line 9, in <module>
    sys.exit(main())
             ^^^^^^
  File "C:\Users\1\anaconda3\envs\example\Lib\site-packages\chemex\chemex.py", line 91, in main
    args.func(args)
  File "C:\Users\1\anaconda3\envs\example\Lib\site-packages\chemex\chemex.py", line 79, in run
    run_fit(args, experiments)
  File "C:\Users\1\anaconda3\envs\example\Lib\site-packages\chemex\chemex.py", line 43, in run_fit
    run_methods(experiments, methods, args.output, args.plot)
  File "C:\Users\1\anaconda3\envs\example\Lib\site-packages\chemex\optimize\fitting.py", line 149, in run_methods
    run_grid(
  File "C:\Users\1\anaconda3\envs\example\Lib\site-packages\chemex\optimize\gridding.py", line 255, in run_grid
    grid_result = run_group_grid(group, grid, path, fitmethod)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1\anaconda3\envs\example\Lib\site-packages\chemex\optimize\gridding.py", line 73, in run_group_grid
    fileout.write(print_header(group_grid))
  File "C:\Users\1\anaconda3\envs\example\Lib\encodings\cp1251.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode characters in position 35-36: character maps to <undefined>`

Method file: 
`[STEP1]
INCLUDE = "ALL"                                                                                 
GRID    = [
    "[KEX_AB] = log(100.0, 600.0, 10)",
    "[PB] = log(0.03, 0.15, 10)",
    "[DW_AB] = lin(0.0, 10.0, 5)",
]

[STEP2]
FIX = ["DW_AB", "R2_A"]`

P.S. Unfortunately I cannot attach the file directly, only a screenshot
![Method](https://github.com/gbouvignies/ChemEx/assets/158455398/9ec67f54-bdd9-496f-a2cc-81a7f369a3da)

Thank you for your help!
Best wishes, Nataliia

**Comment by gbouvignies** [comment]
It appears the issue may stem from the default system encoding being set to cp1251 (Cyrillic alphabets). I'll update ChemEx to explicitly enforce UTF-8 encoding for outputs, which should help avoid such errors. I'll work on implementing this solution.

**Comment by gbouvignies** [comment]
I've made changes to the code to tackle the problem. Would you mind trying out the revised version from the main branch? For evaluation, you can set it up in a fresh environment and use pip to install it with the following command:
```bash
pip install git+https://github.com/gbouvignies/ChemEx
```
I would greatly value your input to confirm that the adjustments have successfully addressed the issue.

**Comment by gbouvignies** [comment]
I am closing the issue for now, but feel free to reopen it necessary.

**Comment by MsMorozka** [comment]
Good morning, Dear Professor. I'm afraid that the problem on my Windows (where I have a Cyrillic alphabets) has not been resolved, I still get the same error. However, I tried the same code on Linux, where the Cyrillic alphabet is not installed at all and the search grid starts without problems.
