### ISSUE TITLE
Regular expressions

### ISSUE THREAD

**Issue by viochemist** [gbouvignies/ChemEx#2]
It would be useful to have the ability to use regular expressions in the parameter and methods files. For instance, instead of saying:

dw,I019HD = fix
dw,I111HD = fix
dw,I213HD = fix
...

using 

dw,I.+HD = fix

**Comment by gbouvignies** [comment]
Got it to work in the new in the new (not yet available) version...

**Comment by viochemist** [comment]
Is this in 0.6.1, or just point_to_profile?

**Comment by gbouvignies** [comment]
This is just point_to_profile... 

Your comment makes me realize that the actual solution does not fully satisfy your first comment.

Now, what can be done is select specific nuclei, like:

    dw_ab, NUC->HD = fix

But it is not possible to select 'HD' nuclei of all isoleucine residues, as in your example. Something I should work on.

**Comment by gbouvignies** [comment]
As mentioned in the previous comment, it is possible to select parameters depending on the same atom type (e.g. "NUC->H) or nucleus site (e.g. "NUC->HD"). I don't plan on implementing anything further than that (like selecting based on the residue type).
I'm closing the issue, but feel free to re-open it if you feel like it is an important feature to have.
