### ISSUE TITLE
The 'bootstrap' setuptools script prevents installation on my system

### ISSUE THREAD

**Issue by gbouvignies** [gbouvignies/chemex#21]
The 'bootstrap' setuptools script `ez_setup.py` does not play well with my config. Here is the error message I obtain after typing `pip install .` in the 'chemex' dir:

    Processing /Users/gbouvignies/PycharmProjects/chemex
    Complete output from command python setup.py egg_info:
    
    The required version of setuptools (>=28.8.0) is not available,
    and can't be installed while this script is running. Please
    install a more recent version first, using
    'easy_install -U setuptools'.
    
    (Currently using setuptools 27.2.0 (/Users/gbouvignies/miniconda3/envs/chemex/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg))
    
    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 2 in /var/folders/t4/l6qq_2px2mz2h1ksgg07s8580000gn/T/pip-4aiixteg-build/

According to the [Python Packaging User Guide](https://packaging.python.org/current/) as well as [PEP 453](https://www.python.org/dev/peps/pep-0453/) and [PEP 477](http://legacy.python.org/dev/peps/pep-0477/), `pip` should already be installed if Python 2 >=2.7.9 or Python 3 >=3.4 is used. As this version of chemex is intended for Python 3 >=3.4, this means that `setuptools` should already be there. Is there any reason to keep the bootstrap script then?

**Comment by reneeotten** [comment]
hhmm... the whole idea behind the boostrap script was that it would update setuptools to the latest version, but apparently that doesn't work very well. To be honest I have never really studied the best-practices in packaging/installing python packages (and wasn't aware of the "ensurepip" thing), but it seems that the links you provided give some good suggestions. I have not really used "pip" before, I typically install everything through MacPorts but just tried it out and it works fine.

I guess we can just drop the ez_setup.py boostrap file then (just make sure to remove the entries in setup.py as well).

**Comment by gbouvignies** [comment]
Alright, I will remove it then.

From what I understand, distributing Python packages is far from being a solved problem... Even though the currently recommended tools (`setuptools`, `pip` and `virtualenv`) made things much easier, they are not perfect, especially when parts of the package require to be compiled (like `numpy`). Actually an increasing amount of people (myself included) are turning to [Conda](http://conda.pydata.org/docs/), which, in addition to be an extremely easy-to-use and convenient package manager, provides precompilled package.
