### ISSUE TITLE
code formatting

### ISSUE THREAD

**Issue by reneeotten** [gbouvignies/chemex#22]
In [this commit](https://github.com/gbouvignies/chemex/commit/0d2e277bc8f8eb311dfe8312c4f8020f6433b152) you formatted the code. While I like most of the changes, I am not a big fan of all the extra whitespace introduced in dictionaries and such (e.g., chemex/bases/three_state/ixyzsxyz.py). I am not sure whether or not this follows the conventions, but I'd be inclined to say no.

I suppose you used some automated tool (which one)? I would certainly prefer an IDE independent tool and personally like "yapf", but haven't used any of them for real. It would be a good idea, however, to settle on something soon-ish and always run that over the code before pushing - it's kind of annoying to have these re-formats show up as changes and needing to merge them...

**Comment by gbouvignies** [comment]
Hey Renee, I usually closely follow [PEP 8](https://www.python.org/dev/peps/pep-0008/) guidelines for code formatting, except when these become too inconvenient – as for the limit of 79 characters per line that I decided to push to 120 (PyCharm default). To help me with that I usually use the automatic code formatting tool of PyCharm (pretty decent). However this time I played (too much?) with the settings, which added these extra-spaces. I'm totally fine removing them and keep the code as close as possible to PEP 8 conventions. Is that OK with you ?

Regarding the use of an IDE independent tool like "yapf", I think it would be a great idea. However I haven't figured out yet how to configure it to keep some specific formatting that I use to improve ChemEx code readability (see `compute_liouvillian` in `chemex/bases/ref.py`). If you find a way, I'll be more than happy to use it.

**Comment by reneeotten** [comment]
Perfect! I agree that readability is important and especially for all the matrices and functions in chemex/bases/*. You can tell "yapf" easily to ignore parts of your code as is described [here](https://github.com/google/yapf#why-does-yapf-destroy-my-awesome-formatting). I just tested it and that works as advertised. 

I am still in the process of looking at the code and fixing some stuff on the way and can add statements for "yapf" in the code when going through the files. I think I can send a pull-request with my changes in a few days. If you want you can wait for that, and we can discuss it in more detail then  - otherwise, please go ahead and try it yourself.
