### ISSUE TITLE
pick_cest program does not launch (fix suggested)

### ISSUE THREAD

**Issue by FrederikTheisen** [gbouvignies/ChemEx#229]
Hi

I've got an issue launching the pick_cest program on an install done today.

I get an error with too many arguments on line 51 in the chemex/tools/pick_cest/buttons.py file.

I resolved the issue by removing the empty string input:
self.spin_system = SpinSystem("")
has been changed to:
self.spin_system = SpinSystem()

I've not looked at how the change affects the functionality in detail, but peak picking works with the change.

Cheers,
Fred

**Comment by gbouvignies** [comment]
Hi Fred,

Thank you for reporting the issue with the pick_cest program and suggesting a fix. I have applied your change, and the fix is now live.

Cheers,
Guillaume
