### ISSUE TITLE
aborting fitting

### ISSUE THREAD

**Issue by chriswaudby** [gbouvignies/ChemEx#25]
I've just noticed that in the from_point_to_profile branch, ctrl+c/command+. no longer works to abort the fitting - it seems to carry on in a separate thread so even after being returned to the command prompt the fitting just continues until I manually kill the process.

**Comment by reneeotten** [comment]
hi Chris, 

I'm having difficulties in reproducing the behavior you describe... If I hit "Ctrl-C" during a minimization it will show " -- Keyboard Interrupt: minimization stopped" and stop that fit. It will, however, try to write the results of the last iteration to the output files. In case you press "Ctrl-C" again, it tells me " - Plotting cancelled" and return to the command prompt. As far as I can tell there are no processes running anymore. 

Can you provide a bit more information? For example how did you installed it (e.g., are you using Anaconda), is there a specific experiment that shows this (or is it reproducible for all the included examples), ....? I just started looking at the code for real a few weeks back, so it's totally possible that I am missing something obvious - if that's the case, then Guillaume will probably have more insights.

**Comment by chriswaudby** [comment]
Hi Renee,

OK, so this is a bit puzzling, there seems to be some variation in behaviour depending what’s running. If I run the 3-state in-phase 15N CEST example, I get the following output – in each case, hitting ctrl+c kills the current minimisation and moves on to the next nucleus or fitting step. Might be nice to be able to kill the fitting in one go, but at least it makes some sense:

* * * * * * * * * * * * * * * * * * * * * * * * *
*      ________                   ______        *
*     / ____/ /_  ___  ____ ___  / ____/  __    *
*    / /   / __ \/ _ \/ __ `__ \/ __/ | |/_/    *
*   / /___/ / / /  __/ / / / / / /____>  <      *
*   \____/_/ /_/\___/_/ /_/ /_/_____/_/|_|      *
*                                               *
*   Analysis of NMR Chemical Exchange data      *
*                                               *
*   Version: 0.6.0+70.g133933c.dirty            *
*                                               *
* * * * * * * * * * * * * * * * * * * * * * * * *



Reading Experimental Data
=========================

File Name                                     Experiment                Profiles                 
---------                                     ----------                --------                 
experiments/cest_n15_500ms_13Hz.cfg           cest.ip                   16                       
experiments/cest_n15_500ms_26Hz.cfg           cest.ip                   16                       


Reading Default Parameters
==========================

File Name: parameters/params_n15.cfg

Section                                       Matches                       
-------                                       -------                       
[global]                                     
  (pb)                                        1                             
  (pc)                                        1                             
  (kex_ab)                                    1                             
  (kex_bc)                                    1                             
  (kex_ac)                                    1                             
  (dw_ab)                                     16                            
  (dw_ac)                                     16                            
  (r1_a)                                      16                            
  (r2_a)                                      16                            
[cs_a]                                        16                            
[dw_ab]                                       16                            
[dw_ac]                                       16                            


Fit
===


 step 1 
--------

[NUC->13N, T->1.0C]
Chi2 / Reduced Chi2:
  * 2.234e+03 / 1.861e+01
  * 5.404e+02 / 4.503e+00
  * 3.987e+02 / 3.323e+00
^C
 -- Keyboard Interrupt: minimization stopped

[NUC->26N, T->1.0C]
Chi2 / Reduced Chi2:
  * 5.066e+03 / 4.222e+01
  * 1.625e+03 / 1.354e+01
  * 1.131e+03 / 9.423e+00
^C
 -- Keyboard Interrupt: minimization stopped

[NUC->28N, T->1.0C]
Chi2 / Reduced Chi2:
  * 9.844e+02 / 8.204e+00
  * 2.907e+02 / 2.423e+00
  * 1.629e+02 / 1.358e+00
^C
 -- Keyboard Interrupt: minimization stopped

[NUC->29N, T->1.0C]
Chi2 / Reduced Chi2:
  * 2.367e+03 / 1.973e+01
  * 6.628e+02 / 5.523e+00
^C
 -- Keyboard Interrupt: minimization stopped

[NUC->33N, T->1.0C]
Chi2 / Reduced Chi2:
  * 4.019e+03 / 3.349e+01
  * 1.236e+03 / 1.030e+01
^C
 -- Keyboard Interrupt: minimization stopped

[NUC->37N, T->1.0C]
Chi2 / Reduced Chi2:
  * 3.859e+03 / 3.216e+01
  * 1.217e+03 / 1.014e+01
  * 7.418e+02 / 6.182e+00
^C
 -- Keyboard Interrupt: minimization stopped

[NUC->41N, T->1.0C]
Chi2 / Reduced Chi2:
  * 5.353e+03 / 4.461e+01
  * 2.029e+03 / 1.691e+01
^C
 -- Keyboard Interrupt: minimization stopped

[NUC->42N, T->1.0C]
Chi2 / Reduced Chi2:
  * 4.580e+03 / 3.817e+01
  * 1.318e+03 / 1.098e+01
  * 6.597e+02 / 5.497e+00
^C
 -- Keyboard Interrupt: minimization stopped

[NUC->43N, T->1.0C]
Chi2 / Reduced Chi2:
  * 2.172e+03 / 1.810e+01
  * 9.436e+02 / 7.864e+00
  * 4.960e+02 / 4.133e+00
^C
 -- Keyboard Interrupt: minimization stopped

[NUC->50N, T->1.0C]
Chi2 / Reduced Chi2:
  * 2.368e+03 / 1.973e+01
  * 7.751e+02 / 6.459e+00
^C
 -- Keyboard Interrupt: minimization stopped

[NUC->52N, T->1.0C]
Chi2 / Reduced Chi2:
  * 2.121e+03 / 1.767e+01
  * 1.103e+03 / 9.191e+00
  * 7.597e+02 / 6.331e+00
^C
 -- Keyboard Interrupt: minimization stopped

[NUC->55N, T->1.0C]
Chi2 / Reduced Chi2:
  * 5.115e+03 / 4.263e+01
  * 2.507e+03 / 2.089e+01
^C
 -- Keyboard Interrupt: minimization stopped

[NUC->59N, T->1.0C]
Chi2 / Reduced Chi2:
  * 1.318e+03 / 1.098e+01
  * 6.795e+02 / 5.662e+00
  * 5.049e+02 / 4.207e+00
^C
 -- Keyboard Interrupt: minimization stopped

[NUC->66N, T->1.0C]
Chi2 / Reduced Chi2:
  * 7.617e+02 / 6.348e+00
  * 3.146e+02 / 2.622e+00
  * 2.551e+02 / 2.126e+00
^C
 -- Keyboard Interrupt: minimization stopped

[NUC->67N, T->1.0C]
Chi2 / Reduced Chi2:
  * 2.680e+03 / 2.233e+01
  * 1.022e+03 / 8.518e+00
^C
 -- Keyboard Interrupt: minimization stopped

[NUC->68N, T->1.0C]
Chi2 / Reduced Chi2:
  * 5.129e+03 / 4.274e+01
  * 2.246e+03 / 1.872e+01
^C
 -- Keyboard Interrupt: minimization stopped

Final Chi2        : 1.226e+04
Final Reduced Chi2: 6.384e+00

 step 2 
--------

Chi2 / Reduced Chi2:
^C
 -- Keyboard Interrupt: minimization stopped

Final Chi2        : 1.226e+04
Final Reduced Chi2: 6.394e+00

 step 3 
--------

Chi2 / Reduced Chi2:
  * 1.226e+04 / 6.398e+00
^C
 -- Keyboard Interrupt: minimization stopped

Final Chi2        : 1.226e+04
Final Reduced Chi2: 6.398e+00


Writing Results
===============


File(s):
  * Output/parameters.fit
  * Output/constraints.fit
  * Output/cest_ip_13hz_500ms_499mhz_1c.dat
  * Output/cest_ip_26hz_500ms_499mhz_1c.dat
  * Output/statistics.fit


Plotting Data
=============


File(s):
  * Output/Plots/cest_ip_13hz_500ms_499mhz_1c.pdf [.fit]
^C - Plotting cancelled



In contrast, for my own case (also a 3-state in-phase 15N CEST fit) when I hit ctrl+c I get dumped to the command prompt, and the minimisation keeps spitting trundling on in the background until I kill it:


* * * * * * * * * * * * * * * * * * * * * * * * *
*      ________                   ______        *
*     / ____/ /_  ___  ____ ___  / ____/  __    *
*    / /   / __ \/ _ \/ __ `__ \/ __/ | |/_/    *
*   / /___/ / / /  __/ / / / / / /____>  <      *
*   \____/_/ /_/\___/_/ /_/ /_/_____/_/|_|      *
*                                               *
*   Analysis of NMR Chemical Exchange data      *
*                                               *
*   Version: 0.6.0+70.g133933c.dirty            *
*                                               *
* * * * * * * * * * * * * * * * * * * * * * * * *



Reading Experimental Data
=========================

File Name                                     Experiment                Profiles                 
---------                                     ----------                --------                 
experiments/37-CEST-800-15Hz-N.cfg            cest.ip                   1                        
experiments/37-CEST-800-60Hz-N.cfg            cest.ip                   1                        
experiments/37-CEST-800-15Hz-U.cfg            cest.ip2                  1                        
experiments/37-CEST-800-60Hz-U.cfg            cest.ip2                  1                        


Reading Default Parameters
==========================

File Name: parameters/params.cfg

Section                                       Matches                       
-------                                       -------                       
[default]                                    
  (pb)                                        1                             
  (pc)                                        1                             
  (kex_ab)                                    1                             
  (kex_bc)                                    1                             
  (kex_ac)                                    1                             
  (r1_a)                                      1                             
  (r1_b)                                      1                             
  (r2_a)                                      1                             
[cs_a]                                        1                             
[dw_ac]                                       1                             
[dw_ab]                                       1                             


Fit
===


 step 1 - fit N and U shifts 
-----------------------------

Chi2 / Reduced Chi2:
^C
 -- Keyboard Interrupt: minimization stopped


[gustav:3-state-fitting/chemex-dev/37oC] chris% Final Chi2        : 3.048e+03
Final Reduced Chi2: 9.406e+00

 step 2 - fit I shift 
----------------------

Chi2 / Reduced Chi2:
  * 3.048e+03 / 9.435e+00

[gustav:3-state-fitting/chemex-dev/37oC] chris%   * 1.165e+03 / 3.608e+00

[gustav:3-state-fitting/chemex-dev/37oC] chris%   * 4.454e+02 / 1.379e+00

[gustav:3-state-fitting/chemex-dev/37oC] chris% ps
  PID TTY           TIME CMD
27440 ttys001    0:00.25 -tcsh
27614 ttys002    0:00.46 -tcsh
30393 ttys002    0:26.16 /Users/chris/anaconda/envs/chemex/bin/python /Users/chris/anaconda/envs/chemex/bin/chemex fit -e experiments/37-CEST-800-15Hz-N.cfg experiments/37-CEST-800-60H
27638 ttys003    0:00.13 -tcsh
29758 ttys004    0:00.21 -tcsh
30250 ttys004    0:00.01 /bin/sh /Users/chris/NMR/nmrPipe/nmrbin.mac/gnuplot
30255 ttys004    0:00.08 /Users/chris/NMR/Gnuplot.app/Contents/Resources/bin/gnuplot-4.2.6
30256 ttys004    0:00.15 gnuplot_x11
[gustav:3-state-fitting/chemex-dev/37oC] chris%   * 3.985e+02 / 1.234e+00

[gustav:3-state-fitting/chemex-dev/37oC] chris% kill 30393


Any ideas? I’m using a clean conda environment (python 3.5.2, numpy 1.11.2, scipy 0.18.1, lmfit v0.9.5). I’m running chemex form just after the merge #23 (16 Nov).

Cheers,

Chris

**Comment by chriswaudby** [comment]
Aha… the problem (as with so many) seems to lie with csh!

When chemex is run from a script with '#!/bin/csh’ the problem strikes - with ‘#!/bin/sh’ the problem is solved.

**Comment by reneeotten** [comment]
okay... we'll that's annoying, but avoiding `csh` for now isn't too bad ;) I have no idea why there would be a difference in behavior depending on the shell and Google doesn't tell me directly either. Perhaps @gbouvignies is actually aware of this since all his scripts for the examples use `sh` already.

**Comment by gbouvignies** [comment]
Thanks Chris for bringing this issue to the table. This behaviour is really confusing to me. I actually don't know whether this is a feature or a bug of `csh`. I tried to google it, but had no luck so far. For the time being, I guess it is better to avoid using `csh` script altogether.
