### ISSUE TITLE
consistent output for CEST/CPMG experiments

### ISSUE THREAD

**Issue by reneeotten** [gbouvignies/chemex#32]
Currently, we write .pdf/.fit/.exp files in the Plots directory for CEST, but only .pdf and .fit files for CPMG. Let's decide on what output files we want, the information they should contain, and generate the same output for all experiment types.

**Comment by gbouvignies** [comment]
The .fit/.exp files should contain the back-calculated/experimental values showed in the plot, respectively, so that users can remake plots.  

We should definitely make it consistent for all experiments.

**Comment by reneeotten** [comment]
thanks, having them consistent and compatible with ConfigParser!
