### ISSUE TITLE
Problem in the output

### ISSUE THREAD

**Issue by ag83uk** [gbouvignies/ChemEx#41]
On MacOS Mojave I can see chemex running but it stops here I cannot find a solution

Thanks for the help

Best

Angelo

File(s):
  * Output/Plots/2_5ppm.pdf [.fit, .exp]
2018-11-13 15:46:34.452 python[1044:14198] -[NSApplication _setup:]: unrecognized selector sent to instance 0x7fc015ae5820
2018-11-13 15:46:34.457 python[1044:14198] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSApplication _setup:]: unrecognized selector sent to instance 0x7fc015ae5820'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff2c3a7e65 __exceptionPreprocess + 256
	1   libobjc.A.dylib                     0x00007fff583fe720 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff2c42522d -[NSObject(NSObject) __retain_OA] + 0
	3   CoreFoundation                      0x00007fff2c349820 ___forwarding___ + 1486
	4   CoreFoundation                      0x00007fff2c3491c8 _CF_forwarding_prep_0 + 120
	5   libtk8.6.dylib                      0x0000001a15aec295 TkpInit + 408
	6   libtk8.6.dylib                      0x0000001a15a5c69a Initialize + 2457
	7   _tkinter.cpython-37m-darwin.so      0x0000001a158bede8 Tcl_AppInit + 88
	8   _tkinter.cpython-37m-darwin.so      0x0000001a158be94a _tkinter_create + 794
	9   python                              0x00000001009f82d6 _PyMethodDef_RawFastCallKeywords + 230
	10  python                              0x0000000100b2c621 call_function + 257
	11  python                              0x0000000100b2a13b _PyEval_EvalFrameDefault + 41963
	12  python                              0x0000000100b1eb9a _PyEval_EvalCodeWithName + 426
	13  python                              0x00000001009f70a7 _PyFunction_FastCallDict + 231
	14  python                              0x0000000100a74471 slot_tp_init + 193
	15  python                              0x0000000100a7e351 type_call + 241
	16  python                              0x00000001009f7d79 _PyObject_FastCallKeywords + 185
	17  python                              0x0000000100b2c6af call_function + 399
	18  python                              0x0000000100b2a3c6 _PyEval_EvalFrameDefault + 42614
	19  python                              0x00000001009f7b68 function_code_fastcall + 120
	20  python                              0x0000000100b2c5d5 call_function + 181
	21  python                              0x0000000100b2a13b _PyEval_EvalFrameDefault + 41963
	22  python                              0x0000000100b1eb9a _PyEval_EvalCodeWithName + 426
	23  python                              0x00000001009f70a7 _PyFunction_FastCallDict + 231
	24  python                              0x00000001009fad02 method_call + 130
	25  python                              0x00000001009f8732 PyObject_Call + 130
	26  python                              0x0000000100b2a52f _PyEval_EvalFrameDefault + 42975
	27  python                              0x0000000100b1eb9a _PyEval_EvalCodeWithName + 426
	28  python                              0x00000001009f70a7 _PyFunction_FastCallDict + 231
	29  python                              0x0000000100b2a52f _PyEval_EvalFrameDefault + 42975
	30  python                              0x0000000100b1eb9a _PyEval_EvalCodeWithName + 426
	31  python                              0x00000001009f81a3 _PyFunction_FastCallKeywords + 195
	32  python                              0x0000000100b2c5d5 call_function + 181
	33  python                              0x0000000100b2a3c6 _PyEval_EvalFrameDefault + 42614
	34  python                              0x0000000100b1eb9a _PyEval_EvalCodeWithName + 426
	35  python                              0x00000001009f81a3 _PyFunction_FastCallKeywords + 195
	36  python                              0x0000000100b2c5d5 call_function + 181
	37  python                              0x0000000100b2a0af _PyEval_EvalFrameDefault + 41823
	38  python                              0x00000001009f7b68 function_code_fastcall + 120
	39  python                              0x0000000100b2c5d5 call_function + 181
	40  python                              0x0000000100b2a317 _PyEval_EvalFrameDefault + 42439
	41  python                              0x0000000100b1eb9a _PyEval_EvalCodeWithName + 426
	42  python                              0x00000001009f81a3 _PyFunction_FastCallKeywords + 195
	43  python                              0x0000000100b2c5d5 call_function + 181
	44  python                              0x0000000100b2a3c6 _PyEval_EvalFrameDefault + 42614
	45  python                              0x00000001009f7b68 function_code_fastcall + 120
	46  python                              0x0000000100b2c5d5 call_function + 181
	47  python                              0x0000000100b2a317 _PyEval_EvalFrameDefault + 42439
	48  python                              0x00000001009f7b68 function_code_fastcall + 120
	49  python                              0x0000000100b2c5d5 call_function + 181
	50  python                              0x0000000100b2a317 _PyEval_EvalFrameDefault + 42439
	51  python                              0x00000001009f7b68 function_code_fastcall + 120
	52  python                              0x0000000100b2c5d5 call_function + 181
	53  python                              0x0000000100b2a13b _PyEval_EvalFrameDefault + 41963
	54  python                              0x00000001009f7b68 function_code_fastcall + 120
	55  python                              0x0000000100b2c5d5 call_function + 181
	56  python                              0x0000000100b2a317 _PyEval_EvalFrameDefault + 42439
	57  python                              0x0000000100b1eb9a _PyEval_EvalCodeWithName + 426
	58  python                              0x0000000100b73b70 PyRun_FileExFlags + 256
	59  python                              0x0000000100b7336c PyRun_SimpleFileExFlags + 364
	60  python                              0x0000000100b9e8b0 pymain_main + 8912
	61  python                              0x00000001009cc710 main + 128
	62  libdyld.dylib                       0x00007fff594cd08d start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
./run.sh: line 7:  1044 Abort trap: 6           chemex fit -e Experiments/19Hz_500ms_*cfg -p Parameters/par.cfg -m Methods/met.cfg -d 2st.pb_kex -o Output

**Comment by gbouvignies** [comment]
Hi Angelo,

The issue seems to come from `matplotlib`, as reported elsewhere (see https://github.com/fpavogt/fcmaker/issues/12). Interestingly I am also running Mac OS Mojave but don't have any issue. Can you `import matplotlib` in a python terminal?

I believe the bug has been reported. One can only hope a fix will soon be deliverd. Meanwhile, a potential workaround could be to change the backend used by matplotlib to `TkAgg`. This can be done via the file `matplotlibrc` as described [here](https://matplotlib.org/users/customizing.html#the-matplotlibrc-file).

**Comment by gbouvignies** [comment]
It seems that using the version 2 of `matplotlib` resolves the problem for now. To do so, one can run the command: `conda install matplotlib=2` in the `chemex` conda environment. 

I close the issue as it does not depend on chemex directly.
