### ISSUE TITLE
"kba" is rarely equal to kex*pa or kex-kab

### ISSUE THREAD

**Issue by viochemist** [gbouvignies/ChemEx#46]
The kba value output in "parameters.fit" is almost never correct and I haven't been able to track down why. My hunch is that in "constraints", the "pa" constraint is listed after the kab and kba constraints. Here's an example of my output. 

[GLOBAL]
KAB, T->25.0C = 3.41490e+01 +/- 1.13594e+01 ; constrained
KBA, T->25.0C = 4.74533e+02 +/- 3.01160e+02 ; constrained
KEX_AB, T->25.0C = 5.27259e+02 +/- 3.22016e+02
PA, T->25.0C = 9.35233e-01 +/- 1.94003e-02 ; constrained
PB, T->25.0C = 6.47671e-02 +/- 1.94003e-02

I'm running the miniconda3 2018 version of chemex. 2st.pb_kex model, cpmg.x_ip

**Comment by reneeotten** [comment]
I am back to some data fitting again as well and I see the same thing indeed. Haven't spent the time yet to try and track this down, but we certainly should...

**Comment by gbouvignies** [comment]
This is now resolved.
