### ISSUE TITLE
Chemex will not run

### ISSUE THREAD

**Issue by smzaharias** [gbouvignies/ChemEx#47]
Hi all,

I am new to chemex and I am having some trouble getting the program to run. I keep getting the following error whenever I try to run the program on anaconda. I even get this error when I try to run analyze the example data provided in this Github. Any help would be greatly appreciated!
![Capture](https://user-images.githubusercontent.com/89660170/131173235-e42118b4-ad03-40e7-b368-44801b40045e.PNG)

**Comment by gbouvignies** [comment]
Hi @smzaharias,
The error message comes form the fact that you're using examples designed for a different version of ChemEx (yet to be released) than the one you're currently using. You can get the examples corresponding to version 2018.10.3  at [this address](https://github.com/gbouvignies/ChemEx/tree/2018.10.3).
