### ISSUE TITLE
X11 dependence can cause chemex and terminal to hang

### ISSUE THREAD

**Issue by viochemist** [gbouvignies/ChemEx#50]
This may be very specific to my situation, but worth mentioning as I don't know why there's an X11 dependence to begin with (probably matplotlib).  

How to replicate issue:

Host: Windows 10, without running Xming/XLaunch
Remote: Ubuntu 18.04.1
Environment: VS Code with "Remote-SSH" and "Remote X11" enabled
Command: Any 'chemex' command will cause the terminal to hang, even Ctrl-C will not end the execution attempt. A second terminal needs to be opened to run 'killall chemex' to regain control of the first terminal.

Workarounds:

A) Run XLaunch on host before connecting to remote
B) Disable "Remote X11", restart Code, and reconnect to remote

**Comment by gbouvignies** [comment]
Is it still an issue?
