### ISSUE TITLE
Document how to run tests

### ISSUE THREAD

**Issue by pacho2** [gbouvignies/ChemEx#51]
While building chemex I wondered about how to run the tests properly:
python3.9 -m pytest -vv -ra -l -Wdefault
=============================================================================================== test session starts ===============================================================================================
platform linux -- Python 3.9.7, pytest-6.2.5, py-1.10.0, pluggy-1.0.0 -- /usr/bin/python3.9
cachedir: .pytest_cache
rootdir: /var/tmp/portage/sci-chemistry/chemex-2021.4.0_p6/work/ChemEx-2021.4.0-dev6
plugins: pkgcore-0.12.8
collected 0 items                                                                                                                                                                                                 

============================================================================================== no tests ran in 1.48s ==============================================================================================

Thanks a lot :)

**Comment by gbouvignies** [comment]
@pacho2 No test has been implemented yet.

**Comment by pacho2** [comment]
Thanks for the info!
