### ISSUE TITLE
In experiments.toml file: ''type'' must be provided ?

### ISSUE THREAD

**Issue by paulschanda** [gbouvignies/ChemEx#53]
Hi Guillaume,
installing today the new version of ChemEx (2018.10.3) I see that the file structure changed.
When I try to run the examples provided (eg examples/Experiments/CPMG_15N_TR) I get the following error:
"
Experiments/500mhz.toml                       
In the section 'experiment' of Experiments/500mhz.toml, ''type'' must be provided!
"
As this already happens to the examples, I have not managed to get my data fitted.

Which are the "types" implemented?
cheers.
Paul

**Comment by gbouvignies** [comment]
Hi Paul,

The examples go with the version available in the master branch.  This is a developper version (2021.4.0-dev6) that I hope to finalize in the coming weeks. It will come with some documentation, a bunch of new experiments and hopefully nice new features.

You can get it [there](https://github.com/gbouvignies/ChemEx/releases/tag/2021.4.0-dev6) or you can install it directly using pip: 

`pip install git+https://github.com/gbouvignies/chemex.git`

Note that this is a developper version and some stuff in the UI may change before the final version.

Cheers,
Guillaume

**Comment by paulschanda** [comment]
Thank you, Guillaume.Indeed, I was surprised that the version number (2018) did not quite look like the most recent.I am looking forward to nice new features then.Bloch-McConnell type R1rho experiments would be such a nice new feature, for example :-) R1rho for solids (NERRD) would be an extra nice feature...Anyhow, thanks, even without R1rho it is very useful.All the best,Paulfrom a mobile device with auto-correction function. I apologize for possible typos or unexpected wording.
-------- Ursprüngliche Nachricht --------Von: Guillaume Bouvignies ***@***.***> Datum: 22.12.21  22:50  (GMT+01:00) An: gbouvignies/ChemEx ***@***.***> Cc: paulschanda ***@***.***>, Author ***@***.***> Betreff: Re: [gbouvignies/ChemEx] In experiments.toml file: ''type'' must be
  provided ? (Issue #53) 
Hi Paul,
The examples go with the version available in the master branch.  This is a developper version (2021.4.0-dev6) that I hope to finalize in the coming weeks. It will come with some documentation, a bunch of new experiments and hopefully nice new features.
You can get it there or you can install it directly using pip:
pip install git+https://github.com/gbouvignies/chemex.git
Note that this is a developper version and some stuff in the UI may change before the final version.
Cheers,
Guillaume
