### ISSUE TITLE
The "easy" install method is outdated

### ISSUE THREAD

**Issue by viochemist** [gbouvignies/ChemEx#59]
The "easy" method of installing chemex installs the 2018 version and does not contain examples or documentation. A new, preferred installation method is recommended.

**Comment by gbouvignies** [comment]
I agree the state of the GitHub repo does not allow for a nice starting with ChemEx right. New version with an associated website including documented examples (with links to their GitHub location) is coming soon. See the PR #56 for the updated codebase. I'll soon push another PR with a draft of the website.

**Comment by gbouvignies** [comment]
Things should be better now with the website hosting the documentation and referencing the different examples.
