### ISSUE TITLE
CEST multiple B1 field strengths possible?

### ISSUE THREAD

**Issue by FrederikTheisen** [gbouvignies/ChemEx#63]
I'm looking to use ChemEx to analyze some CEST data. In order to both get resolution and signal intensity I performed the CEST experiment with three different B1 fields and I would like to fit these data sets simultaneously. 
I've previously tried this using RingNMR, but that software lacks constraint options when fitting globally.

Is this possible using ChemEx?

Regards
Frederik

**Comment by FrederikTheisen** [comment]
Providing multiple experiment files using '-e file1 file2' appears to do what I wanted to do.

**Comment by gbouvignies** [comment]
Hi Frederik,

Good you found the solution by yourself. A CEST example with multiple B1 files is provided [here](https://github.com/gbouvignies/ChemEx/tree/master/examples/Experiments/CEST_15N). Note that not only can ChemEx fit multiple CEST experiments together, it can also mix different kinds of experiments together (for example, CEST and CPMG) as illustrated [there](https://github.com/gbouvignies/ChemEx/tree/master/examples/Combinations/2stBinding).

**Comment by FrederikTheisen** [comment]
Thank you for the reply. 
I saw the example bash script, but since I don't have a lot of bash experience, I didn't realize that the '*' mean all files and not 'insert your filename here'. Learning something new all the time.

If I may ask, there is also a parameter called 'TAUC_A', which I'm not sure what to do with. Looking at the math, I cannot seem to locate a variable named tau so maybe the variable is not used for CEST data processing?

One feature that would be nice is the possibility of fitting a 'no exchange' function to the data for comparison with the exchange function. Comparing individually fitted AIC and RMSD of 'no ex' vs 'ex' could then be used to decide which residues to be used for a global analysis.

**Comment by FrederikTheisen** [comment]
The `-d 1st` appears to work nicely. It also splits every residue into a separate fitting group. Is there an easy way to split every residue into separate groups when fitting using an exchange model?

**Comment by viochemist** [comment]
I can't tell the specifics, but if the correlation matrix of the fitted parameters is singular, ChemEx can not provide a reliable error estimate (ie. the error is basically infinite). Guillaume can give a more accurate response. Long story short is, the profile does not have enough information to estimate the error.

I run many instances of ChemEx at a time and do not have any unusual behavior. Of course, make sure you are not outputting to the same directories, or reading inputs that could change from another instance's output.
