### ISSUE TITLE
Ignore sidebands

### ISSUE THREAD

**Issue by viochemist** [gbouvignies/ChemEx#7]
It would be useful if ChemEx would ignore data at the locations of decoupling sidebands. This would require inputing the 1H decoupling pulse, but everything else should be available. I wrote a script to do this with the data, but for an easy user experience it would be ideal for ChemEx to take care of it automagically.

**Comment by gbouvignies** [comment]
We could have a 'filter_sidebands' parameter in the 'experiment.cfg' file that would contain the frequency period (in Hz) at which you expect sidebands to be. Of course this would be based on the initial value of the position of the ground state dip.

Does this sound like an OK solution to you?

**Comment by gbouvignies** [comment]
https://github.com/gbouvignies/ChemEx/commit/8e7bc3356901856f62579d8ccaf6ffd8d316900f adds two parameters in CEST experiments to filter specific offsets: `filter_offsets` contains the offsets in Hz to be filtered out and `filter_bandwidths` define the corresponding range of offsets to be filtered out. The offsets are defined relative to the resonance position of state 'a' as set at the beginning of the fit.

For example:
```
filter_offsets = -100 0 100
filter_bandwidths = 20 20 20
```
to filter out points within [-110;-90] or [-10;10] or [90;110] Hz from the main dip.
