### ISSUE TITLE
Ks p-value 

### ISSUE THREAD

**Issue by smzaharias** [gbouvignies/ChemEx#75]
So I have been comparing the KS p-value for the 2 different plots. One that has a very good fit and another where the fit isn't as good. For some reason the plots with the worse fits are giving lower KS p-values. I might be misinterpretting the KS P-values, but I thought that fits with lower KS p-values indicate that the fit is better. Do you have any idea why this is happening?

**Comment by gbouvignies** [comment]
The Kolmogorov-Smirnov (KS) test is used to determine if two distributions differ significantly. A lower KS p-value indicates that the null hypothesis (that the two distributions are the same) can be rejected, meaning a poorer fit. Thus, the plots with worse fits should indeed have lower KS p-values, consistent with your observation.
