### ISSUE TITLE
experiment references disappeared

### ISSUE THREAD

**Issue by viochemist** [gbouvignies/chemex#8]
Experiment references are not showing up when following the info options, ie.

chemex info cpmg n_cw_cpmg

"""
15N - Pure In-phase Nitrogen CPMG
=================================

Analyzes 15N chemical exchange in the presence of high power 1H CW
    decoupling during the CPMG block. This keeps the spin system purely in-phase
    throughout, and is calculated using the 6x6, single spin matrix:

    [ Nx(a), Ny(a), Nz(a), Nx(b), Ny(b), Nz(b) ]

    Off resonance effects are taken into account. The calculation is designed
    specifically to analyze the experiment found in the reference.

Experimental parameters
-----------------------
  * resonance_id
  * h_larmor_frq
  * temperature
  * carrier
  * time_t2
  * time_equil
  * pw
  * ncyc

Fitted parameters (by default)
------------------------------
  * pb
  * kex
  * dw
  * i0
  * r_nxy

Fixed parameters (by default)
-----------------------------
  * r_nz
  * dr_nxy
  * cs
"""

**Comment by gbouvignies** [comment]
Reference is back!

chemex info cpmg n_cw_cpmg

15N - Pure In-phase Nitrogen CPMG
=================================

Analyzes 15N chemical exchange in the presence of high power 1H CW decoupling 
during the CPMG block. This keeps the spin system purely in-phase throughout, 
and is calculated using the 6x6, single spin matrix:

[ Nx(a), Ny(a), Nz(a), Nx(b), Ny(b), Nz(b) ]

Off resonance effects are taken into account. The calculation is designed
specifically to analyze the experiment found in the reference:

*Journal of Physical Chemistry B (2008) v.112, p.5898-5904*


Experimental parameters
-----------------------
  * resonance_id
  * h_larmor_frq
  * temperature
  * carrier
  * time_t2
  * time_equil
  * pw
  * ncyc


Fitted parameters (by default)
------------------------------
  * pb
  * kex
  * dw
  * i0
  * r_nxy


Fixed parameters (by default)
-----------------------------
  * r_nz
  * dr_nxy
  * cs
